name: Deploy to Amazon EC2

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-0671beccbd2630a

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Repository checked out successfully"
          ls -la

      - name: Configure AWS credentials
        run: |
          echo "Starting AWS credential configuration..."
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
          echo "EC2_INSTANCE_ID=${{ env.EC2_INSTANCE_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "EC2_INSTANCE_ID=$EC2_INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "Environment variables set successfully"

      - name: Verify AWS credentials
        run: |
          echo "Verifying AWS credentials..."
          aws sts get-caller-identity
          echo "AWS CLI identity verified successfully"

      - name: Get instance public IP
        id: get-instance-ip
        run: |
          echo "Getting EC2 instance public IP..."
          aws ec2 describe-instances --instance-id ${env.EC2_INSTANCE_ID} --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text
          echo "PUBLIC_IP=$?" >> $GITHUB_OUTPUT
          echo "Instance public IP retrieved successfully"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get-instance-ip.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # Install Docker if not already installed
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Copy required files
            mkdir -p /home/ubuntu/app
            git clone https://github.com/PrateekAnand3101/Django-website /home/ubuntu/app

            # Build and run the Docker image
            cd /home/ubuntu/app
            docker build -t django-website .
            docker stop django-website || true
            docker rm django-website || true
            docker run -d --name django-website -p 8000:8000 django-website

      - name: Clean up
        run: |
          echo "Cleaning up..."
          docker stop django-website || true
          docker rm django-website || true
          echo "Cleanup completed"
