name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-0671beccbd2630a

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          EC2_INSTANCE_ID: ${{ env.EC2_INSTANCE_ID }}
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
          echo "EC2_INSTANCE_ID=${{ env.EC2_INSTANCE_ID }}" >> $GITHUB_ENV
      - name: Verify AWS credentials
        run: aws sts get-caller-identity
      - name: Get instance public IP
        id: get-instance-ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-id ${{ env.EC2_INSTANCE_ID }} \
            --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
            --output text)
          echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV
          echo "::set-output name=public_ip::${PUBLIC_IP}"
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            mkdir -p /home/ubuntu/app
            git clone https://github.com/PrateekAnand3101/Django-website /home/ubuntu/app
            cd /home/ubuntu/app
            docker build -t django-website .
            docker stop django-website || true
            docker rm django-website || true
            docker run -d --name django-website -p 8000:8000 django-website
      - name: Clean up
        run: |
          docker stop django-website || true
          docker rm django-website || true
