name: Deploy to Amazon EC2

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-0671bebccbdd2630a

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get instance public IP
        id: get-instance-ip
        run: |
          aws ec2 describe-instances --instance-id ${env.EC2_INSTANCE_ID} --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text
          echo "PUBLIC_IP=$?" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get-instance-ip.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # Install Docker if not already installed
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Copy required files
            mkdir -p /home/ubuntu/app
            git clone https://github.com/PrateekAnand3101/Django-website /home/ubuntu/app

            # Build and run the Docker image
            cd /home/ubuntu/app
            docker build -t django-website .
            docker stop django-website || true
            docker rm django-website || true
            docker run -d --name django-website -p 8000:8000 django-website
