name: Deploy to Amazon EC2
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-0671beccbd2630a
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.AWS_REGION }}

      - name: Get instance public IP
        id: get-instance-ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-id ${{ env.EC2_INSTANCE_ID }} \
            --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
            --output text)
          echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to app directory
            cd /home/ubuntu/app || mkdir -p /home/ubuntu/app

            # Pull latest changes if repo exists, clone if it doesn't
            if [ -d .git ]; then
              git fetch --all
              git reset --hard origin/main
            else
              git clone https://github.com/PrateekAnand3101/Django-website .
            fi

            # Stop and remove existing container
            docker stop django-website || true
            docker rm django-website || true

            # Remove old image to force rebuild
            docker rmi django-website || true

            # Build with no-cache to ensure fresh build
            docker build --no-cache -t django-website .

            # Run new container
            docker run -d --name django-website \
              -p 8000:8000 \
              --restart unless-stopped \
              django-website
